### ISSUE TITLE
Scaling factor intermittently resets to default value

### ISSUE THREAD

**Issue by jjst** [ertug/autohidpi#7] opened 2015-02-18 21:02 UTC
On my Chromebook Pixel (resolution 2560x1700), the scaling factor sometimes randomly gets reset to its default value. I haven't been able to identify what triggers this behaviour but it seems to happen when switching between windows, e.g. tab-switching between Firefox and another application. I'm not changing the zoom level manually.

I'm using AutoHiDPI 1.1 on Firefox 35.0.1 for Ubuntu. The HiDPI screen width is set to '2400'  and the Pixel ratio to '2.0' in the add-on config.

The issue doesn't appear when the add-on is disabled and the scaling factor is manually set to 2.0 in Firefox's config.

I'm aware this might be tricky to debug without more info as to what might be causing the problem so if there's any more data I can give to help debug the issue I'm happy to oblige.

**Comment by ertug** [comment] 2015-02-19 20:32
I think I catched this bug while adding custom pixel ratio support and made a fix.

Can you try 1.2?
https://addons.mozilla.org/en-US/firefox/addon/autohidpi/versions/1.2

**Comment by jjst** [comment] 2015-02-20 09:10
I just installed 1.2, I'll test over the next few days and tell you how it goes.

**Comment by fenderglass** [comment] 2015-03-03 06:47
Still have this (or similar) bug with 3200x1800 display and firefox 36 from fedora repos :(
After restarting browser, scale drops back to 1 and I can switch it to 2 by making an arbitrary modification of the input field in preferences (like adding space)

**Comment by jjst** [comment] 2015-03-08 20:58
Yeah, I'm seeing the same behaviour unfortunately.

**Comment by rubo77** [comment] 2015-05-11 12:26
Same Problem here on Ubuntu 14.10 with 3200x1800 resolution. I can reproduce it:

You first have to change the focussed Tab in your Firefox at least once and then use Alt+TAB to switch to another application

**Comment by rubo77** [comment] 2015-05-22 14:43
Now it messes around with `pixelsPerPx` though deactivated.

Maybe this addon is obsolete since Firefox 38?

It seems Firefox is changing this value also itself

**Comment by jadelord** [comment] 2016-02-08 18:18
I see the same thing happen while window switching with Alt-Tab (randomly, not always)

PS: I am using AutoHiDPI (from addons.mozilla.org) on my Dell XPS 13 running ArchLinux (GNOME).

**Comment by nikkolasg** [comment] 2016-03-23 20:45
Hi, 
Same here. Using:
- AwesomeWM
- Firefox 45.0.1
It happens most of the time when I go to another desktop/application and then comes back in Firefox.
Do you have any idea what could cause this behavior ?
I'm not at all a GTK / Firefox / graphic expert but if you have an idea (but not the time ;), I'd be happy to help.

**Comment by btittelbach** [comment] 2016-05-28 00:30
I also experience this issue using:

* AutoHiDPI 1.2.1-signed.1-signed
* Firefox 46.0.1
* Ubuntu 15.10 running gnome-shell

**Comment by ertug** [comment] 2016-05-28 19:33
Thank you for the comments!
Please try the new version, it should be fixed:
https://addons.mozilla.org/en-US/firefox/addon/autohidpi/versions/?page=1#version-2.0.0

**Closed by ertug** 2016-05-28 19:33 UTC
